spring:
  application:
    name: spotnik-ingestion
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wikidata
  kafka:
    consumer:
      auto-offset-reset: earliest


server:
  port: 8082
  servlet:
    context-path: /spotnik-ingestion


kafka:
  bootstrap-servers: localhost:9092

spotnik:
  ingestion:
    batch-size: 1000
