spring:
  application:
    name: spotnik
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wikidata
application:
  nerservice:
    port: 5001
    host: localhost
    protocol: http
    endpoints:
      extractEntities: /extract_entities

server:
  port: 8080
  servlet:
    context-path: /spotnik